version: 2
updates:
  # Maintain dependencies for Flutter/Dart (pub)
  - package-ecosystem: "pub"
    directory: "/" # Location of your pubspec.yaml
    schedule:
      interval: "monthly"
    # Group updates for `pub` dependencies to reduce PR noise
    groups:
      pub-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of your .github/workflows/
    schedule:
      interval: "monthly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
