name: budgetiser

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.6.0+8

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.2
  flutter_colorpicker: ^1.0.3
  sqflite_sqlcipher: ^2.1.1
  flutter_markdown: ^0.6.9+1
  provider: ^6.0.2
  jiffy: ^6.2.1
  shared_preferences: ^2.0.13
  path: ^1.8.1
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  package_info_plus: ^4.0.2
  equations: ^5.0.1
  intl: ^0.18.1

  # MIT License
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  sqflite_common_ffi: ^2.3.0
  test: ^1.24.4

flutter_icons:
  android: true
  image_path: "assets/images/logo_white_background.png"
  adaptive_icon_foreground: "assets/images/logo_white_foreground.png"
  adaptive_icon_background: "#3282b8"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/how-to.md
    - assets/images/how_to/account.png
    - assets/images/how_to/category.png
    - assets/images/how_to/transaction.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: LogoIcon
      fonts:
        - asset: fonts/logo_icon.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
