/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class LogoIcon {
  LogoIcon._();

  static const _kFontFam = 'LogoIcon';
  static const String? _kFontPkg = null;

  static const IconData budgetiserIcon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
