name: Build

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: set up Flutter
      uses: subosito/flutter-action@v1.4.0
      with:
        flutter-version: '2.0.1'
    - name: Create the keystore
      env:
        KEYSTORE_BASE64: ${{secrets.KEYSTORE_BASE64}}
      run: |
        # import keystore from secrets
        echo "${KEYSTORE_BASE64///}" | base64 --decode > $RUNNER_TEMP/my_production.keystore
    - name: Restore packages
      run: flutter pub get
    - name: Build Android App Bundle
      run: flutter build appbundle --release
    - name: Sign Android App Bundle
      run: jarsigner -keystore $RUNNER_TEMP/my_production.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEYSTORE_PASSWORD_ALIAS }} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/release/app-release-signed.aab build/app/outputs/bundle/release/*.aab YOUR_PRODUCTION_ALIAS
    - name: Publish Android Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: release-aab-signed
        path: build/app/outputs/bundle/release/app-release-signed.aab
