name: bump version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
      - name: Print version
        run: |
          echo "semVer: ${{ steps.gitversion.outputs.majorMinorPatch }}"
      - name: get previous build number and incrment in by 1
        # read the build number from pubspec.yaml, compare old and new version -> increase build number if different
        run: |
          export BUILD_NUMBER=$(sed -E -n 's/version. [0-9]+\.[0-9]+\.[0-9]+\+([0-9]+)/\1/p' pubspec.yaml)

          # Get the current version from the YAML file
          OLD_VERSION=$(sed -E -n 's/version. ([0-9]+\.[0-9]+\.[0-9]+)\+[0-9]+/\1/p' pubspec.yaml)

          # Compare the current version with GitVersion
          if [ "$OLD_VERSION" != "${{ steps.gitversion.outputs.semVer }}" ]; then
            # Increment BUILD_NUMBER if the versions are different
            export BUILD_NUMBER=$((BUILD_NUMBER + 1))
            echo "incremented!!"
          fi
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
      - name: Update version in YAML
        run: sed -i -E "s/(version. )[0-9]+\.[0-9]+\.[0-9]+\+([0-9]+)/\1${{ steps.gitversion.outputs.majorMinorPatch }}+$BUILD_NUMBER/g" pubspec.yaml
      # - name: commit
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
      #     message: "bump version ${{ steps.gitversion.outputs.majorMinorPatch }}"
      - name: Commit and push
        uses: Amraneze/push-to-protected-branch@v1.5.0
        with:
          repository: ${{ github.repository }}
          branch_name: main
          github_token: ${{ secrets.PAT_CLASSIC_REPO }}
          commit_message: "bump version ${{ steps.gitversion.outputs.majorMinorPatch }}"
          files_to_commit: "pubspec.yaml"
