name: bump version

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Bump version
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4
        with:
          configFilePath: gitversion.yml

      - name: Print version
        run: |
          echo "semVer: ${{ steps.gitversion.outputs.majorMinorPatch }}"

      - name: Check if version changed
        id: check_version
        run: |
          OLD_VERSION=$(sed -E -n 's/version. ([0-9]+\.[0-9]+\.[0-9]+)\+[0-9]+/\1/p' pubspec.yaml)
          if [ "$OLD_VERSION" = "${{ steps.gitversion.outputs.majorMinorPatch }}" ]; then
            echo "No new version. Cancelling workflow."
            echo "cancelled=true" >> $GITHUB_OUTPUT
          else
            echo "cancelled=false" >> $GITHUB_OUTPUT
          fi

      - name: Cancel if no new version
        if: steps.check_version.outputs.cancelled == 'true'
        run: exit 0

      - name: get previous build number and increment in by 1
        if: steps.check_version.outputs.cancelled == 'false'
        run: |
          export BUILD_NUMBER=$(sed -E -n 's/version. [0-9]+\.[0-9]+\.[0-9]+\+([0-9]+)/\1/p' pubspec.yaml)
          export BUILD_NUMBER=$((BUILD_NUMBER + 1))
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Update version in YAML
        if: steps.check_version.outputs.cancelled == 'false'
        run: sed -i -E "s/(version. )[0-9]+\.[0-9]+\.[0-9]+\+([0-9]+)/\1${{ steps.gitversion.outputs.majorMinorPatch }}+$BUILD_NUMBER/g" pubspec.yaml

      - name: commit
        if: steps.check_version.outputs.cancelled == 'false'
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add .
          git commit -m "bump version ${{ steps.gitversion.outputs.majorMinorPatch }} [skip ci]"

      - name: Pushing to the protected branch 'main'
        if: steps.check_version.outputs.cancelled == 'false'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PAT_PUSH_PROTEDTED }}
          branch: main
