name: flutter build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          cd budgetiser 
          flutter pub get
          flutter build apk --split-per-abi --no-tree-shake-icons
      - uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: budgetiser/build/app/outputs/flutter-apk/
