name: flutter build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          cd budgetiser 
          flutter pub get
          flutter test
          flutter build apk --no-tree-shake-icons
          flutter build appbundle
