name: Flutter tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Flutter tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - run: flutter pub get

      - run: flutter test
