name: Flutter tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Flutter tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - run: flutter pub get

      # needed for sqflite on linux https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi
      - run: sudo apt-get -y install libsqlite3-0 libsqlite3-dev

      - run: flutter test
