name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Create the keystore
      env:
        KEYSTORE_BASE64: ${{secrets.KEYSTORE_BASE64}}
      run: |
        # import keystore from secrets
        echo $KEYSTORE_BASE64 | base64 -di > $RUNNER_TEMP/my_production.keystore
    - name: Restore packages
      run: |
        flutter pub get
    - name: Build Android App Bundle
      run: |
        flutter build appbundle --release --no-tree-shake-icons
    - name: Sign Android App Bundle
      run: jarsigner -keystore $RUNNER_TEMP/my_production.keystore -storepass ${{secrets.KEYSTORE_PASSWORD}} -keypass ${{secrets.KEYSTORE_PASSWORD_ALIAS}} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/release/app-release-signed.aab build/app/outputs/bundle/release/app-release.aab upload
        cd budgetiser
        flutter pub get
    - name: Publish Android Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/app-release.aab
    - name: Publish Android Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: release-aab-signed
        path: build/app/outputs/bundle/release/app-release-signed.aab

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Download bundle dependencies
      run: |
        gem install bundler:2.0.2
        bundle config path vendor/bundle
        bundle install
    - name: Release to Google Play (production)
      env:
        SUPPLY_PACKAGE_NAME: de.budgetiser.budgetiser
        SUPPLY_JSON_KEY_DATA: ${{secrets.GOOGLE_SERVICE_ACCOUNT_KEY}}
      run: |
        bundle exec fastlane run supply \
        aab:build/app/outputs/bundle/release/app-release-signed.aab \
        track:internal