name: release internal playstore

# releases to playstore internal branch
# if the version is not changed to the previous release (done by autoincrement on develop) this failes

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Create Java Upload-Keystore
        env:
          KEYSTORE_BASE64: ${{secrets.KEYSTORE_BASE64}}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -di > $RUNNER_TEMP/my_production.keystore

      - name: Restore Flutter-Packages
        run: |
          flutter pub get

      - name: Build Android App (AAB and APK)
        run: |
          flutter build appbundle --release --no-tree-shake-icons
          flutter build apk --release --no-tree-shake-icons

      - name: Sign Android App Bundle
        run: jarsigner -keystore $RUNNER_TEMP/my_production.keystore -storepass ${{secrets.KEYSTORE_PASSWORD}} -keypass ${{secrets.KEYSTORE_PASSWORD_ALIAS}} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/release/app-release-signed.aab build/app/outputs/bundle/release/app-release.aab upload

      - name: Export AAB (local)
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Export signed AAB (local)
        uses: actions/upload-artifact@v4
        with:
          name: release-aab-signed
          path: build/app/outputs/bundle/release/app-release-signed.aab

      - name: Export APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Publish to Google Play (internal)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.GOOGLE_SERVICE_ACCOUNT_KEY}}
          packageName: de.budgetiser.budgetiser
          releaseFiles: build/app/outputs/bundle/release/app-release-signed.aab
          track: internal
          status: completed

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve Version
        id: retrieve_version
        run: |
          YAML_VERSION=$(sed -E -n 's/version. ([0-9]+\.[0-9]+\.[0-9]+)\+[0-9]+/\1/p' pubspec.yaml)
          echo "version=${YAML_VERSION}" >> $GITHUB_OUTPUT

      - name: Download signed AAB
        uses: actions/download-artifact@v5
        with:
          name: release-aab-signed
          path: build/app/outputs/bundle/release/

      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/

      - name: Download APK
        uses: actions/download-artifact@v5
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.retrieve_version.outputs.version }}"
          prerelease: true
          generate_release_notes: true
          files: |
            build/app/outputs/bundle/release/app-release-signed.aab
            build/app/outputs/flutter-apk/app-release.apk
