name: release internal playstore

# releases to playstore internal branch
# if the version is not changed to the previous release (done by autoincrement on develop) this failes

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout (release)"
        uses: actions/checkout@v3
        with:
          ref: "release"

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17.x"

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Create Java Upload-Keystore
        env:
          KEYSTORE_BASE64: ${{secrets.KEYSTORE_BASE64}}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -di > $RUNNER_TEMP/my_production.keystore

      - name: Restore Flutter-Packages
        run: |
          flutter pub get

      - name: Build Android App Bundle (release)
        run: |
          flutter build appbundle --release --no-tree-shake-icons

      - name: Sign Android App Bundle
        run: jarsigner -keystore $RUNNER_TEMP/my_production.keystore -storepass ${{secrets.KEYSTORE_PASSWORD}} -keypass ${{secrets.KEYSTORE_PASSWORD_ALIAS}} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/release/app-release-signed.aab build/app/outputs/bundle/release/app-release.aab upload

      - name: Export AAB (local)
        uses: actions/upload-artifact@v1
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Export signed AAB (local)
        uses: actions/upload-artifact@v1
        with:
          name: release-aab-signed
          path: build/app/outputs/bundle/release/app-release-signed.aab

      - name: Publish to Google Play (internal)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.GOOGLE_SERVICE_ACCOUNT_KEY}}
          packageName: de.budgetiser.budgetiser
          releaseFiles: build/app/outputs/bundle/release/app-release-signed.aab
          track: internal
          status: completed

      - name: "Checkout (main)"
        uses: actions/checkout@v3
        with:
          ref: "main"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ steps.gitversion.outputs.majorMinorPatch }}"
          tag_exists_error: true

      - name: Create Github pre-release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/app-release-signed.aab" # todo add .apk file
          generateReleaseNotes: true
          prerelease: true
          tag: "v${{ steps.gitversion.outputs.majorMinorPatch }}"
